apiVersion: v1
kind: Pod
metadata:
  name: mydb-pod
  labels:
    name: mydb
spec:
  containers:
  - name: postgresdb
    image: postgres
    env:
    - name: POSTGRES_PASSWORD
      value: mysecretpassword
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 5432
